[general]
import = ["./themes/dracula.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "SemiBold"

[font.italic]
family = "VictorMono Nerd Font"
style = "Medium Italic"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

[terminal]
osc52 = "CopyPaste"

[window]
padding.x = 4
padding.y = 4
