---
- name: Install Alacritty via Homebrew
  homebrew_cask:
    name: alacritty
    state: present

- name: Create .config directory
  file:
    path: "{{ config_home }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Link Alacritty config directory
  file:
    src: "{{ playbook_dir }}/../config/alacritty"
    dest: "{{ config_home }}/alacritty"
    state: link
    force: true

- name: Disable font smoothing for Alacritty
  command: defaults write org.alacritty AppleFontSmoothing -int 0
